package io.github.josemodi97.daraja4j.maven;

/**
 * The extra integration-example file written by {@link Daraja4jInitMojo}
 * for a given {@code -Ddaraja4j.framework=...} choice - an STK Push callback
 * servlet/listener, since that's the operation almost every integration
 * starts with. {@code null} (via {@link #forFramework(String)}) for
 * {@code plain}, which only gets the placeholder properties file.
 */
final class FrameworkExample {

    final String relativePath;
    final String content;

    private FrameworkExample(String relativePath, String content) {
        this.relativePath = relativePath;
        this.content = content;
    }

    static FrameworkExample forFramework(String framework) {
        switch (framework) {
            case "servlet":
                return new FrameworkExample("daraja4j/DarajaStkCallbackServlet.java", SERVLET_EXAMPLE);
            case "jakarta":
                return new FrameworkExample("daraja4j/DarajaStkCallbackServlet.java", JAKARTA_EXAMPLE);
            case "spring-boot2":
                return new FrameworkExample("daraja4j/DarajaPaymentListener.java", springBootExample("boot2"));
            case "spring-boot3":
                return new FrameworkExample("daraja4j/DarajaPaymentListener.java", springBootExample("boot3"));
            default:
                return null;
        }
    }

    private static final String SERVLET_EXAMPLE =
            "package daraja4j;\n"
                    + "\n"
                    + "// Generated by daraja4j:init. Move this into your own package, and\n"
                    + "// replace the onSuccess/onFailure bodies below with real logic.\n"
                    + "// Requires the daraja4j-servlet dependency.\n"
                    + "\n"
                    + "import io.github.josemodi97.daraja4j.servlet.Daraja4jStkCallbackServletHandler;\n"
                    + "import java.io.IOException;\n"
                    + "import javax.servlet.ServletException;\n"
                    + "import javax.servlet.annotation.WebServlet;\n"
                    + "import javax.servlet.http.HttpServlet;\n"
                    + "import javax.servlet.http.HttpServletRequest;\n"
                    + "import javax.servlet.http.HttpServletResponse;\n"
                    + "\n"
                    + "@WebServlet(\"/daraja4j/stk-callback\")\n"
                    + "public class DarajaStkCallbackServlet extends HttpServlet {\n"
                    + "\n"
                    + "    private final Daraja4jStkCallbackServletHandler handler = new Daraja4jStkCallbackServletHandler()\n"
                    + "            .onSuccess((result, req, res) -> {\n"
                    + "                // TODO: mark the order paid, e.g.:\n"
                    + "                // orderService.markPaid(result.getCheckoutRequestId(), result.getMpesaReceiptNumber());\n"
                    + "            })\n"
                    + "            .onFailure((result, req, res) -> {\n"
                    + "                // TODO: log the failure, e.g.:\n"
                    + "                // log.warn(\"daraja4j: STK push failed - \" + result.getResultDesc());\n"
                    + "            });\n"
                    + "\n"
                    + "    @Override\n"
                    + "    protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {\n"
                    + "        handler.handle(req, res);\n"
                    + "    }\n"
                    + "}\n";

    private static final String JAKARTA_EXAMPLE =
            "package daraja4j;\n"
                    + "\n"
                    + "// Generated by daraja4j:init. Move this into your own package, and\n"
                    + "// replace the onSuccess/onFailure bodies below with real logic.\n"
                    + "// Requires the daraja4j-jakarta dependency.\n"
                    + "\n"
                    + "import io.github.josemodi97.daraja4j.jakarta.Daraja4jStkCallbackServletHandler;\n"
                    + "import jakarta.servlet.ServletException;\n"
                    + "import jakarta.servlet.annotation.WebServlet;\n"
                    + "import jakarta.servlet.http.HttpServlet;\n"
                    + "import jakarta.servlet.http.HttpServletRequest;\n"
                    + "import jakarta.servlet.http.HttpServletResponse;\n"
                    + "import java.io.IOException;\n"
                    + "\n"
                    + "@WebServlet(\"/daraja4j/stk-callback\")\n"
                    + "public class DarajaStkCallbackServlet extends HttpServlet {\n"
                    + "\n"
                    + "    private final Daraja4jStkCallbackServletHandler handler = new Daraja4jStkCallbackServletHandler()\n"
                    + "            .onSuccess((result, req, res) -> {\n"
                    + "                // TODO: mark the order paid, e.g.:\n"
                    + "                // orderService.markPaid(result.getCheckoutRequestId(), result.getMpesaReceiptNumber());\n"
                    + "            })\n"
                    + "            .onFailure((result, req, res) -> {\n"
                    + "                // TODO: log the failure, e.g.:\n"
                    + "                // log.warn(\"daraja4j: STK push failed - \" + result.getResultDesc());\n"
                    + "            });\n"
                    + "\n"
                    + "    @Override\n"
                    + "    protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {\n"
                    + "        handler.handle(req, res);\n"
                    + "    }\n"
                    + "}\n";

    private static String springBootExample(String bootPackage) {
        return "package daraja4j;\n"
                + "\n"
                + "// Generated by daraja4j:init. Move this into your own package, and\n"
                + "// replace the TODOs below with real logic. Requires\n"
                + "// daraja4j-spring-" + bootPackage + "-starter and daraja4j.webhook.stk.enabled=true\n"
                + "// (already added to daraja4j.properties by this same init run).\n"
                + "\n"
                + "import io.github.josemodi97.daraja4j.spring." + bootPackage + ".Daraja4jStkPaymentFailedEvent;\n"
                + "import io.github.josemodi97.daraja4j.spring." + bootPackage + ".Daraja4jStkPaymentVerifiedEvent;\n"
                + "import org.springframework.context.event.EventListener;\n"
                + "import org.springframework.stereotype.Component;\n"
                + "\n"
                + "@Component\n"
                + "public class DarajaPaymentListener {\n"
                + "\n"
                + "    @EventListener\n"
                + "    public void onPaid(Daraja4jStkPaymentVerifiedEvent event) {\n"
                + "        // TODO: mark the order paid, e.g.:\n"
                + "        // orderService.markPaid(event.getResult().getCheckoutRequestId(), event.getResult().getMpesaReceiptNumber());\n"
                + "    }\n"
                + "\n"
                + "    @EventListener\n"
                + "    public void onFailed(Daraja4jStkPaymentFailedEvent event) {\n"
                + "        // TODO: log the failure, e.g.:\n"
                + "        // log.warn(\"daraja4j: STK push failed - \" + event.getResult().getResultDesc());\n"
                + "    }\n"
                + "}\n";
    }
}
